// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgMtSE3EFhs8_oTZfolZ3cIAYIx8yqvU4',
    appId: '1:200056716627:web:4f43d60c8d3e07ced3f5a6',
    messagingSenderId: '200056716627',
    projectId: 'ican-all-aplication',
    authDomain: 'ican-all-aplication.firebaseapp.com',
    storageBucket: 'ican-all-aplication.firebasestorage.app',
    measurementId: 'G-7N4C08DTQ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSY6SCyfyraDzNrEJiZOW_VG1zylHFtiQ',
    appId: '1:200056716627:android:37cf047271a6db5ad3f5a6',
    messagingSenderId: '200056716627',
    projectId: 'ican-all-aplication',
    storageBucket: 'ican-all-aplication.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxMNH4tKWvkSb2HX2fmTlycRemS1CN7hA',
    appId: '1:200056716627:ios:f33e7958aeaffdadd3f5a6',
    messagingSenderId: '200056716627',
    projectId: 'ican-all-aplication',
    storageBucket: 'ican-all-aplication.firebasestorage.app',
    iosBundleId: 'com.example.icanCenterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxMNH4tKWvkSb2HX2fmTlycRemS1CN7hA',
    appId: '1:200056716627:ios:f33e7958aeaffdadd3f5a6',
    messagingSenderId: '200056716627',
    projectId: 'ican-all-aplication',
    storageBucket: 'ican-all-aplication.firebasestorage.app',
    iosBundleId: 'com.example.icanCenterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgMtSE3EFhs8_oTZfolZ3cIAYIx8yqvU4',
    appId: '1:200056716627:web:bae08c0f9cd14517d3f5a6',
    messagingSenderId: '200056716627',
    projectId: 'ican-all-aplication',
    authDomain: 'ican-all-aplication.firebaseapp.com',
    storageBucket: 'ican-all-aplication.firebasestorage.app',
    measurementId: 'G-NRNTW2V8KE',
  );
}
